const nodemailer = require('nodemailer');

let transporter = null;
let testAccount = null;

async function initEmailService() {
  if (process.env.SMTP_HOST) {
    transporter = nodemailer.createTransport({
      host: process.env.SMTP_HOST,
      port: parseInt(process.env.SMTP_PORT) || 587,
      secure: process.env.SMTP_SECURE === 'true',
      auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS
      }
    });
    console.log('Nodemailer initialized with custom SMTP server.');
  } else {
    try {
      console.log('No SMTP config found. Creating Nodemailer Ethereal test account...');
      testAccount = await nodemailer.createTestAccount();
      transporter = nodemailer.createTransport({
        host: 'smtp.ethereal.email',
        port: 587,
        secure: false,
        auth: {
          user: testAccount.user,
          pass: testAccount.pass
        }
      });
      console.log(`Ethereal Test Account Created:`);
      console.log(`  User: ${testAccount.user}`);
      console.log(`  Pass: ${testAccount.pass}`);
      console.log(`  Inbox URL: https://ethereal.email`);
    } catch (err) {
      console.error('Failed to create Nodemailer Ethereal account. Emails will only be logged to console.');
      console.error(err.message);
    }
  }
}

async function sendAlertEmail(sensor) {
  const adminEmail = process.env.ADMIN_EMAIL || 'admin@smartbuilding.com';
  const subject = `⚠️ EMERGENCY ALERT: Smoke Detected in ${sensor.roomName} (Floor ${sensor.floor})`;
  const htmlContent = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #ff4d4d; border-radius: 8px; overflow: hidden; box-shadow: 0 4px 10px rgba(0,0,0,0.1);">
      <div style="background-color: #ff4d4d; color: white; padding: 20px; text-align: center;">
        <h2 style="margin: 0; font-size: 24px;">🚨 Fire & Smoke Emergency Alert</h2>
      </div>
      <div style="padding: 20px; background-color: #ffffff; color: #333333; line-height: 1.6;">
        <p>Hello Administrator,</p>
        <p>A physical sensor has triggered an emergency alert in the building monitoring system:</p>
        
        <table style="width: 100%; border-collapse: collapse; margin: 20px 0;">
          <tr style="background-color: #f8f9fa;">
            <th style="text-align: left; padding: 10px; border-bottom: 1px solid #dddddd;">Sensor ID</th>
            <td style="padding: 10px; border-bottom: 1px solid #dddddd; font-family: monospace; font-weight: bold;">${sensor.sensorId}</td>
          </tr>
          <tr>
            <th style="text-align: left; padding: 10px; border-bottom: 1px solid #dddddd;">Location</th>
            <td style="padding: 10px; border-bottom: 1px solid #dddddd;">${sensor.roomName} (Floor ${sensor.floor})</td>
          </tr>
          <tr style="background-color: #f8f9fa;">
            <th style="text-align: left; padding: 10px; border-bottom: 1px solid #dddddd;">Smoke Level</th>
            <td style="padding: 10px; border-bottom: 1px solid #dddddd; color: #ff4d4d; font-weight: bold;">${sensor.smokeLevel} (MQ-2 analog reading)</td>
          </tr>
          <tr>
            <th style="text-align: left; padding: 10px; border-bottom: 1px solid #dddddd;">Time Detected</th>
            <td style="padding: 10px; border-bottom: 1px solid #dddddd;">${new Date().toLocaleString()}</td>
          </tr>
        </table>
        
        <p style="background-color: #fff3cd; color: #856404; padding: 15px; border-left: 5px solid #ffeeba; border-radius: 4px;">
          <strong>Action Required:</strong> Please check the building's digital twin dashboard immediately and inspect the room. If this is a real emergency, initiate evacuation and emergency procedures.
        </p>
      </div>
      <div style="background-color: #f1f1f1; text-align: center; padding: 15px; font-size: 12px; color: #666666; border-top: 1px solid #eeeeee;">
        This email was automatically generated by the Smart Building IoT Digital Twin platform.
      </div>
    </div>
  `;

  if (transporter) {
    try {
      const info = await transporter.sendMail({
        from: '"Smart Building System" <no-reply@smartbuilding.com>',
        to: adminEmail,
        subject: subject,
        html: htmlContent
      });
      console.log(`[Email Service] Alert email successfully sent to ${adminEmail}`);
      if (testAccount) {
        console.log(`[Email Service] Ethereal View URL: ${nodemailer.getTestMessageUrl(info)}`);
      }
    } catch (err) {
      console.error('[Email Service] Error sending email via SMTP:', err.message);
    }
  } else {
    console.log('=================== EMERGENCY EMAIL LOG ===================');
    console.log(`TO: ${adminEmail}`);
    console.log(`SUBJECT: ${subject}`);
    console.log(`BODY SUMMARY: Smoke level ${sensor.smokeLevel} at ${sensor.roomName}`);
    console.log('===========================================================');
  }
}

module.exports = {
  initEmailService,
  sendAlertEmail
};
